server:
  port: 18085
spring:
  application:
    name: sentinel-spring-cloud-gateway
  cloud:
    gateway:
      enabled: true
      discovery:
        locator:
          lower-case-service-id: true
      routes:
      # Add your routes here.
      - id: test
        uri: http://localhost:8084/
        predicates:
        - Path=/**

    sentinel:
      datasource.ds2.file:
        file: "classpath: gateway.json"
        ruleType: degrade
      transport:
        dashboard: localhost:8080
      filter:
        enabled: true
      scg.fallback:
          mode: response
          response-status: 444
          response-body: 1234
      scg:
        order: -100

management.endpoints.web.exposure.include: "*"